# Generated by Django 3.0.8 on 2020-07-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('contact', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('enrol', models.ManyToManyField(blank=True, to='Admin1.CourseModel')),
            ],
        ),
    ]
