# Generated by Django 3.0.8 on 2020-07-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0003_auto_20200709_2256'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='enrol',
            field=models.ManyToManyField(blank=True, to='Admin1.CourseModel'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='no',
            field=models.IntegerField(auto_created=True, blank=True),
        ),
    ]
