# Generated by Django 3.0.8 on 2020-07-09 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogIn',
            new_name='LogInModel',
        ),
    ]
