# Generated by Django 3.0.8 on 2020-07-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0002_auto_20200709_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='date',
            field=models.DateField(help_text='YY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='time',
            field=models.TimeField(help_text='24 Hours'),
        ),
    ]
